[package]
name = "radix50-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "radix50"
path = "radix50-cli.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radix50 = { path = "../lib" }
docopt = "1"
serde = "1"
